name = "macOS Tray"

[js]
tray = "tray.js"

[chords]
'?=' = { name = "Tray" }
# '=0' = { name = "Tray: Notch", 'js:notch' = [] }
'=1' = { name = "Tray: 1st Item", 'js:tray' = [0] }
'=2' = { name = "Tray: 2nd Item", 'js:tray' = [1] }
'=3' = { name = "Tray: 3rd Item", 'js:tray' = [2] }
'=4' = { name = "Tray: 4th Item", 'js:tray' = [3] }
'=5' = { name = "Tray: 5th Item", 'js:tray' = [4] }
'=6' = { name = "Tray: 6th Item", 'js:tray' = [5] }
'=7' = { name = "Tray: 7th Item", 'js:tray' = [6] }
'=8' = { name = "Tray: 8th Item", 'js:tray' = [7] }
'=9' = { name = "Tray: 9th Item", 'js:tray' = [8] }

'?=-' = { name = "Tray: From End" }
'=-1' = { name = "Tray: 1st End Item", 'js:tray' = [-1] }
'=-2' = { name = "Tray: 2nd End Item", 'js:tray' = [-2] }
'=-3' = { name = "Tray: 3rd End Item", 'js:tray' = [-3] }
'=-4' = { name = "Tray: 4th End Item", 'js:tray' = [-4] }
'=-5' = { name = "Tray: 5th End Item", 'js:tray' = [-5] }
'=-6' = { name = "Tray: 6th End Item", 'js:tray' = [-6] }
'=-7' = { name = "Tray: 7th End Item", 'js:tray' = [-7] }
'=-8' = { name = "Tray: 8th End Item", 'js:tray' = [-8] }
'=-9' = { name = "Tray: 9th End Item", 'js:tray' = [-9] }
'=1/' = { name = "Tray: 1st Item Right Click", 'js:tray' = [0, 'right'] }
'=2/' = { name = "Tray: 2nd Item Right Click", 'js:tray' = [1, 'right'] }
'=3/' = { name = "Tray: 3rd Item Right Click", 'js:tray' = [2, 'right'] }
'=4/' = { name = "Tray: 4th Item Right Click", 'js:tray' = [3, 'right'] }
'=5/' = { name = "Tray: 5th Item Right Click", 'js:tray' = [4, 'right'] }
'=6/' = { name = "Tray: 6th Item Right Click", 'js:tray' = [5, 'right'] }
'=7/' = { name = "Tray: 7th Item Right Click", 'js:tray' = [6, 'right'] }
'=8/' = { name = "Tray: 8th Item Right Click", 'js:tray' = [7, 'right'] }
'=9/' = { name = "Tray: 9th Item Right Click", 'js:tray' = [8, 'right'] }
'=-1/' = { name = "Tray: 1st End Item Right Click", 'js:tray' = [-1, 'right'] }
'=-2/' = { name = "Tray: 2nd End Item Right Click", 'js:tray' = [-2, 'right'] }
'=-3/' = { name = "Tray: 3rd End Item Right Click", 'js:tray' = [-3, 'right'] }
'=-4/' = { name = "Tray: 4th End Item Right Click", 'js:tray' = [-4, 'right'] }
'=-5/' = { name = "Tray: 5th End Item Right Click", 'js:tray' = [-5, 'right'] }
'=-6/' = { name = "Tray: 6th End Item Right Click", 'js:tray' = [-6, 'right'] }
'=-7/' = { name = "Tray: 7th End Item Right Click", 'js:tray' = [-7, 'right'] }
'=-8/' = { name = "Tray: 8th End Item Right Click", 'js:tray' = [-8, 'right'] }
'=-9/' = { name = "Tray: 9th End Item Right Click", 'js:tray' = [-9, 'right'] }

'=b' = { name = "Tray: Battery" }
'=c' = { name = "Tray: Control Center" }
'=t' = { name = "Tray: Time & Date" }

'?=w' = { name = "Tray Wi-Fi" }
'=w' = { name = "Tray: Wi-Fi" }
'=wv' = { name = "Tray Wi-Fi: Vary On/Off" }
